name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        
      - name: Setup Front-end
        run: cd client && npm install && npm run build --if-present
      
      - name: Setup Back-end
        run: cd server && npm install && npm run build --if-present
      
      - name: Run tests
        run: |
          cd client
          npm test
          
          cd ../server
          npm test
